set(CMAKE_SYSTEM_NAME Windows )
set(CMAKE_SYSTEM_PROCESSOR x86)

set(CMAKE_CROSSCOMPILING ON)
set(CMAKE_C_COMPILER_WORKS ON)
set(CMAKE_CXX_COMPILER_WORKS ON)

set(CMAKE_C_COMPILER x86_64-w64-mingw32-gcc)
set(CMAKE_CXX_COMPILER x86_64-w64-mingw32-gcc)
#execute_process(COMMAND x86_64-w64-mingw32-pkg-config --variable pc_path pkg-config OUTPUT_VARIABLE PKG_CONFIG_PATH)
set(ENV{PKG_CONFIG} x86_64-w64-mingw32-pkg-config)
